# Generated by Django 4.2.4 on 2023-10-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vouchers', '0002_alter_vouchers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(blank=True, verbose_name='Fecha del pago')),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto del pago')),
                ('comprobante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.vouchers')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pagos del club',
                'ordering': ['fecha_pago'],
            },
        ),
    ]
