# Generated by Django 4.2.4 on 2023-10-26 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_remove_activities_modified_by'),
        ('partners', '0005_partners_actividades_alter_partners_compite'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comprobante', models.DateField(blank=True, verbose_name='Fecha del comprobante')),
                ('observacion', models.CharField(blank=True, max_length=50, verbose_name='Observacion')),
                ('estado', models.CharField(blank=True, choices=[('0', 'Pagado'), ('1', 'No Pagado'), ('2', 'No Definido')], max_length=1, verbose_name='Estado')),
                ('tipo_pago', models.CharField(blank=True, choices=[('0', 'Efectivo'), ('1', 'Tarjeta'), ('2', 'Transferencia'), ('3', 'No Definido')], max_length=1, verbose_name='Tipo de pago')),
                ('nombre_quien_paga', models.CharField(blank=True, max_length=30, verbose_name='Nombre de la persona que paga')),
                ('fecha_pago', models.DateField(blank=True, verbose_name='Fecha del pago')),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto del pago')),
                ('actividades', models.ManyToManyField(blank=True, to='activities.activities')),
                ('socio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partners')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos del club',
                'ordering': ['-fecha_comprobante'],
            },
        ),
    ]
