# Generated by Django 4.2.4 on 2023-10-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partners_actividades_alter_partners_compite'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pagos', 'verbose_name_plural': 'Pagos del club'},
        ),
        migrations.AddField(
            model_name='payments',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partners.partners'),
            preserve_default=False,
        ),
    ]
