# Generated by Django 4.2.4 on 2023-10-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activities_nombre_actividad_and_more'),
        ('partners', '0006_alter_partners_actividades_alter_partners_compite_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='anio',
            field=models.IntegerField(default=1, max_length=5, verbose_name='Año'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='mes',
            field=models.CharField(choices=[('0', 'Enero'), ('1', 'Febrero'), ('2', 'Marzo'), ('3', 'Abril'), ('4', 'Mayo'), ('5', 'Junio'), ('6', 'Julio'), ('7', 'Agosto'), ('8', 'Septiembre'), ('9', 'Octubre'), ('10', 'Noviembre'), ('11', 'Diciembre')], default=1, max_length=2, verbose_name='Mes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='actividades',
            field=models.ManyToManyField(to='activities.activities'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='estado',
            field=models.CharField(choices=[('0', 'Pagado'), ('1', 'Pago Parcial'), ('2', 'No Definido')], max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='fecha_comprobante',
            field=models.DateField(verbose_name='Fecha del comprobante'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha del pago'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Monto del pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='tipo_pago',
            field=models.CharField(choices=[('0', 'Efectivo'), ('1', 'Mercado Pago'), ('2', 'Transferencia'), ('3', 'No Definido')], max_length=1, verbose_name='Tipo de pago'),
        ),
    ]
