# Generated by Django 4.2.4 on 2023-11-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payments_anio_alter_payments_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='estado',
            field=models.CharField(choices=[('0', 'Pagado'), ('1', 'Pago Parcial'), ('2', 'Pagado y Confirmado'), ('3', 'No Definido')], max_length=1, verbose_name='Estado'),
        ),
    ]
