# Generated by Django 4.2.4 on 2023-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payments_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='fecha_comprobante',
            field=models.DateField(null=True, verbose_name='Fecha del comprobante'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='fecha_pago',
            field=models.DateField(null=True, verbose_name='Fecha del pago'),
        ),
    ]
