# Generated by Django 4.2.4 on 2023-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comprobante', models.DateField(blank=True, verbose_name='Fecha del comprobante')),
                ('observacion', models.CharField(blank=True, max_length=50, verbose_name='Observacion')),
                ('estado', models.CharField(blank=True, choices=[('0', 'Pagado'), ('1', 'No Pagado'), ('2', 'No Definido')], max_length=1, verbose_name='Estado')),
                ('tipo_pago', models.CharField(blank=True, choices=[('0', 'Efectivo'), ('1', 'Tarjeta'), ('2', 'Transferencia'), ('3', 'No Definido')], max_length=1, verbose_name='Tipo de pago')),
                ('nombre_quien_paga', models.CharField(blank=True, max_length=30, verbose_name='Nombre de la persona que paga')),
            ],
        ),
    ]
