# Generated by Django 4.2.4 on 2023-10-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchers',
            options={'ordering': ['fecha_comprobante'], 'verbose_name': 'Comprobante', 'verbose_name_plural': 'Comprobantes del club'},
        ),
    ]
