# Generated by Django 4.2.4 on 2023-10-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activities_modified_by'),
        ('partners', '0005_partners_actividades_alter_partners_compite'),
        ('vouchers', '0002_alter_vouchers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='actividades',
            field=models.ManyToManyField(blank=True, to='activities.activities'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='socio',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='partners.partners'),
            preserve_default=False,
        ),
    ]
