# Generated by Django 4.2.4 on 2023-10-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0004_alter_partners_fecha_nacimiento'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnerXactivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(blank=True, verbose_name='Fecha de inscripción')),
                ('activo', models.BooleanField(default=False, verbose_name='Esta activo?')),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activities')),
                ('socio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partners')),
            ],
            options={
                'verbose_name': 'Socio por actividad',
                'verbose_name_plural': 'Socios por actividades del club',
                'ordering': ['socio'],
            },
        ),
    ]
