# Generated by Django 4.2.4 on 2023-10-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0004_alter_partners_fecha_nacimiento'),
        ('vouchers', '0002_alter_vouchers_options'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='voucherspartnersXactivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activities')),
                ('comprobante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vouchers.vouchers')),
                ('socio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partners')),
            ],
        ),
    ]
