# Generated by Django 4.2.4 on 2023-10-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherspartnersXactivities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherspartnersxactivities',
            options={'ordering': ['comprobante'], 'verbose_name': 'Comprobante de socio por actividad', 'verbose_name_plural': 'Comprobantes de los Socios por actividad'},
        ),
    ]
