# Generated by Django 4.2.4 on 2023-10-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, verbose_name='Año')),
                ('mes', models.CharField(blank=True, max_length=20, verbose_name='Mes')),
                ('valor_clase_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de la clase por consulta')),
                ('valor_mensual_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual fijo')),
                ('valor_mensual_1semana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual por 1 vez semana')),
                ('valor_mensual_2semana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual por 2 veces a la semana')),
                ('valor_clase_3semana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual por 3 veces a la semana ')),
                ('valor_mensual_libre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual libre')),
                ('cuota_social', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cuota Social')),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activities')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios del club',
                'ordering': ['anio'],
            },
        ),
    ]
