# Generated by Django 4.2.4 on 2023-10-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='valor_mensual_libre',
        ),
        migrations.AddField(
            model_name='prices',
            name='mes_impago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mes impago'),
        ),
        migrations.AddField(
            model_name='prices',
            name='valor_fichaje_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor del fichaje anual'),
        ),
        migrations.AddField(
            model_name='prices',
            name='valor_libre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor libre'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='valor_clase_3semana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual por 3 veces a la semana'),
        ),
    ]
