# Generated by Django 4.2.4 on 2023-10-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activities_modified_by'),
        ('prices', '0004_alter_prices_options_alter_prices_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activities'),
        ),
    ]
