# Generated by Django 4.2.4 on 2023-10-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_prices_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='medio_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Medio Mes'),
        ),
        migrations.AddField(
            model_name='prices',
            name='valor_patin3semanaescula',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual de 3 veces por semana de Patín + escuela'),
        ),
        migrations.AddField(
            model_name='prices',
            name='valor_patindanza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual de Patin con danza'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='mes_impago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Recargo'),
        ),
    ]
