# Generated by Django 4.2.4 on 2023-11-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_prices_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='valor_mensual_1semana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mensual por 1 vez a la semana'),
        ),
    ]
