# Generated by Django 4.2.4 on 2023-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_nombre', models.CharField(blank=True, max_length=40, verbose_name='Nombre del municipio')),
                ('localidad_nombre', models.CharField(blank=True, choices=[('0', 'Provincia de Buenos Aires'), ('1', 'Ciudad Autónoma de Buenos Aires')], max_length=1, verbose_name='Nombre de la localidad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['municipio_nombre'],
            },
        ),
    ]
