# Generated by Django 4.2.4 on 2023-10-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(blank=True, max_length=30, verbose_name='Nombre de la actividad')),
                ('tipo_actividad', models.CharField(blank=True, choices=[('0', 'Cuota Social'), ('1', 'Porcentaje'), ('2', 'Alquiler')], max_length=2, verbose_name='Tipo de la actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades del club',
                'ordering': ['nombre_actividad'],
            },
        ),
    ]
