# Generated by Django 4.2.4 on 2023-10-23 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['id'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades del club'},
        ),
        migrations.AddField(
            model_name='activities',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activities',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('0', 'Mensual')], default='0', max_length=2, verbose_name='Tipo de la actividad'),
        ),
    ]
