# Generated by Django 4.2.4 on 2023-10-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activities_options_activities_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='modified_by',
        ),
    ]
