# Generated by Django 4.2.4 on 2023-10-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activities_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('0', 'Mensual'), ('1', 'Porcentaje'), ('2', 'Alquiler')], default='0', max_length=2, verbose_name='Tipo de la actividad'),
        ),
    ]
