# Generated by Django 4.2.4 on 2023-10-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activities_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='nombre_actividad',
            field=models.CharField(max_length=30, verbose_name='Nombre de la actividad'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='tipo_actividad',
            field=models.CharField(choices=[('0', 'Mensual'), ('1', 'Porcentaje'), ('2', 'Alquiler')], default='0', max_length=2, verbose_name='Tipo de la actividad'),
        ),
    ]
