# Generated by Django 4.2.4 on 2023-11-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activities_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='tipo_actividad',
            field=models.CharField(choices=[('0', 'Mensual'), ('1', 'Porcentaje'), ('2', 'Alquiler')], default='0', max_length=2, verbose_name='Tipo de cobro de la actividad'),
        ),
    ]
