# Generated by Django 4.2.4 on 2023-10-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=50, verbose_name='Nombre completo')),
                ('dni', models.IntegerField(blank=True, verbose_name='Dni')),
                ('fecha_nacimiento', models.DateField(blank=True, verbose_name='Fecha de nacimiento:')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, choices=[('0', 'Provincia de Buenos Aires'), ('1', 'Ciudad Autónoma de Buenos Aires')], max_length=2, verbose_name='Distrito')),
                ('telefono1', models.CharField(blank=True, max_length=15, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(blank=True, max_length=15, verbose_name='Telefono 2')),
                ('correo', models.EmailField(blank=True, max_length=40, verbose_name='Email')),
                ('descripcion', models.CharField(blank=True, max_length=50, verbose_name='Descripción')),
                ('apto_fisico', models.BooleanField(default=False, verbose_name='Apto físico')),
                ('fecha_vencimiento_apto_fisico', models.DateField(blank=True, verbose_name='Fecha de vencimiento del apto físico')),
                ('fecha_vencimiento_fichaje', models.DateField(blank=True, verbose_name='Fecha de vencimiento del fichaje')),
                ('compite', models.BooleanField(default=False, verbose_name='Compite?')),
                ('socio_activo', models.BooleanField(default=False, verbose_name='Socio activo')),
                ('localidad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios del club',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
