# Generated by Django 4.2.4 on 2023-10-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('partners', '0002_alter_partners_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='localidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
