# Generated by Django 4.2.4 on 2023-10-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partners_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
