# Generated by Django 4.2.4 on 2023-10-28 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0007_alter_partners_fecha_vencimiento_apto_fisico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
