# Generated by Django 4.2.4 on 2023-11-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_partners_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='fecha_vencimiento_apto_fisico',
            field=models.DateField(verbose_name='Fecha de emisión del apto físico'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='fecha_vencimiento_fichaje',
            field=models.DateField(verbose_name='Fecha de emisión del fichaje'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='telefono1',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono 2'),
        ),
    ]
