# Generated by Django 4.2.4 on 2023-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_alter_partners_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='fecha_vencimiento_apto_fisico',
            field=models.DateField(null=True, verbose_name='Fecha de emisión del apto físico'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='fecha_vencimiento_fichaje',
            field=models.DateField(null=True, verbose_name='Fecha de emisión del fichaje'),
        ),
    ]
