# Generated by Django 4.2.4 on 2023-11-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_alter_partners_fecha_vencimiento_apto_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='fecha_vencimiento_apto_fisico',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión del apto físico'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='fecha_vencimiento_fichaje',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión del fichaje'),
        ),
    ]
