# Generated by Django 4.2.4 on 2023-11-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_alter_partners_fecha_vencimiento_apto_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='telefono1',
            field=models.CharField(max_length=15, verbose_name='Teléfono 1'),
        ),
    ]
