# Generated by Django 4.2.4 on 2023-11-09 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_alter_partners_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='dni',
            field=models.IntegerField(blank=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios en blanco.', regex='^[a-zA-Z\\s]*$')], verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='telefono1',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono 1'),
        ),
    ]
