# Generated by Django 4.2.4 on 2023-11-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_alter_partners_direccion_alter_partners_dni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='fecha_vencimiento_apto_fisico',
            new_name='fecha_emision_apto_fisico',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='fecha_vencimiento_fichaje',
            new_name='fecha_emision_fichaje',
        ),
    ]
