# Generated by Django 4.2.4 on 2023-11-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_alter_partners_distrito_alter_partners_localidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['id'], 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios del club'},
        ),
    ]
