# Generated by Django 4.2.4 on 2023-11-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_localidad_nombre_and_more'),
        ('partners', '0020_alter_partners_apto_fisico_alter_partners_compite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='localidad',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
            preserve_default=False,
        ),
    ]
