# Generated by Django 4.2.4 on 2023-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_alter_partners_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='compite',
            field=models.BooleanField(default=False, verbose_name='Fichado'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='socio_activo',
            field=models.BooleanField(default=False, verbose_name='Socio activo'),
        ),
    ]
