# Generated by Django 4.2.4 on 2023-11-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_alter_partners_compite_alter_partners_socio_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='apto_fisico',
            field=models.BooleanField(default=False, verbose_name='Apto físico'),
        ),
    ]
