# Generated by Django 4.2.4 on 2023-11-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_localidad_nombre_and_more'),
        ('partners', '0024_alter_partners_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
